#!/usr/bin/env bash

###################################
### coletando informações uteis ###
###################################

echo "Prepare seu disco com cfdisk"
echo "1- partição boot, 2-partição Swap, 3-partição Raiz, 4-Partição Home"
sleep 10 
cfdisk
echo "Qual disco será utilizado?"
echo "se for por exemplo sda1 use sda somente" 
read DISC

#formata os Discos

format_disc () {
    echo "Formatando discos..."
    mkfs.fat -F32 /dev/${DISC}1
    mkswap /dev/${DISC}2
    mkfs.ext4 /dev/${DISC}3
    mkfs.ext4 /dev/${DISC}4
    echo "discos formatados"
}

#faz a montagem dos discos e cria as pastas


mount_disc () {
    echo "montando partições..."
    mount /dev/${DISC}3 /mnt
    mkdir -p /mnt/boot/efi
    mkdir -p /mnt/home
    mount /dev/${DISC}1 /mnt/boot/efi
    mount /dev/${DISC}4 /mnt/home
    echo "partições montadas.."
}

#instala o sistema base no disco

pacstrap_disc () {
    reflector 
    echo "instalando sistema base"
    pacstrap /mnt base base-devel linux-lts linux-firmware network-manager-applet networkmanager amd-ucode fwupd dosfstools mtools ntfs-3g dialog sudo nano vim htop reflector
    echo "sistema base instalado"
    echo "gerando tabela fstab..."
    genfstab -U -p /mnt >> /mnt/etc/fstab
    echo "tabela fstab gerada"
}


#inicia os eventos
format_disc
mount_disc
pacstrap_disc




cat <<REALEND > /mnt/next.sh

echo "escolha uma senha para o usuario root"
passwd
echo "Digite um nome de usuario e  aperte <ENTER>"
read USUARIO
useradd -m -g users -G wheel,storage,power -s /bin/bash $USUARIO
echo "digite a senha para o usuario"
passwd $USUARIO
sed -i 's/^# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/' /etc/sudoers

sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf

ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
hwclock --systohc

echo KEYMAP=br-abnt2 >> /etc/vconsole.conf

PACMAN_LIST=(
    grub 
    efibootmgr
    xorg-server
    xorg-xinit
    xorg-apps
    mesa
    xf86-video-amdgpu
    xdg-user-dirs
    gvfs
    qtile
    lxappearance
    intltool
    nitrogen
    picom
    pulseaudio
    pavucontrol
    physlock
    ly
)

#install package pacman
install_pacman() {
  for package in "${PACMAN_LIST[@]}"; do
   sudo pacman -S "$package"  -y --noconfirm
  done
}

install_pacman

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=arch_grub --recheck
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable ly.service
systemctl enable NetworkManager
systemctl enable bluetooth.service 

REALEND


arch-chroot /mnt sh next.sh




